using System;
using UnityEngine;
// generated by Editor/AnimatorAccess ☀
namespace AnimatorAccess
{
	[System.Serializable]
	public class PlayerAnimator : StateMachineBehaviour
	{
		protected Animator _animator;

		public void SetAnimator(Animator animator){ _animator = animator; }

		// Perameters
		// hash values
		protected const int MoveSpeedHash = 526065662;
		protected const int IsJumpHash = 19011116;
		protected const int IsAttackHash = 2145273271;
		protected const int IsFire2Hash = -671287417;
		protected const int TestTriggerHash = 1033918907;

		// parameter setter getter 
		public float GetMoveSpeed(){ return _animator.GetFloat(MoveSpeedHash); }
		public void SetMoveSpeed(float value){ _animator.SetFloat(MoveSpeedHash, value);}
		public bool GetIsJump(){ return _animator.GetBool(IsJumpHash); }
		public void SetIsJump(bool value){ _animator.SetBool(IsJumpHash, value);}
		public bool GetIsAttack(){ return _animator.GetBool(IsAttackHash); }
		public void SetIsAttack(bool value){ _animator.SetBool(IsAttackHash, value);}
		public bool GetIsFire2(){ return _animator.GetBool(IsFire2Hash); }
		public void SetIsFire2(bool value){ _animator.SetBool(IsFire2Hash, value);}
		public void TestTrigger(){ _animator.SetTrigger (TestTriggerHash); } public void ResetTestTrigger() { _animator.ResetTrigger (TestTriggerHash); }

		// State
		public const int StateIdAttack_Fire1 = -375459552;
		public const int StateIdIdle = 1432961145;
		public const int StateIdRun = -827840423;
		public const int StateIdJump = 788460410;
		public const int StateIdKick = -1751635351;
		public const int StateIdScrewKick = -106577475;

		public bool IsAttack_Fire1State(){ return StateIdAttack_Fire1 == _animator.GetCurrentAnimatorStateInfo(0).fullPathHash; }
		public bool IsIdleState(){ return StateIdIdle == _animator.GetCurrentAnimatorStateInfo(0).fullPathHash; }
		public bool IsRunState(){ return StateIdRun == _animator.GetCurrentAnimatorStateInfo(0).fullPathHash; }
		public bool IsJumpState(){ return StateIdJump == _animator.GetCurrentAnimatorStateInfo(0).fullPathHash; }
		public bool IsKickState(){ return StateIdKick == _animator.GetCurrentAnimatorStateInfo(0).fullPathHash; }
		public bool IsScrewKickState(){ return StateIdScrewKick == _animator.GetCurrentAnimatorStateInfo(0).fullPathHash; }

		public virtual void OnStateEnterToAttack_Fire1(Animator animator, AnimatorStateInfo stateInfo){}
		public virtual void OnStateExitFromAttack_Fire1(Animator animator, AnimatorStateInfo stateInfo){}
		public virtual void OnStateMoveAttack_Fire1(Animator animator, AnimatorStateInfo stateInfo){}
		public virtual void OnStateUpdateAttack_Fire1(Animator animator, AnimatorStateInfo stateInfo){}
		public virtual void OnStateIKAttack_Fire1(Animator animator, AnimatorStateInfo stateInfo){}
		public virtual void OnStateEnterToIdle(Animator animator, AnimatorStateInfo stateInfo){}
		public virtual void OnStateExitFromIdle(Animator animator, AnimatorStateInfo stateInfo){}
		public virtual void OnStateMoveIdle(Animator animator, AnimatorStateInfo stateInfo){}
		public virtual void OnStateUpdateIdle(Animator animator, AnimatorStateInfo stateInfo){}
		public virtual void OnStateIKIdle(Animator animator, AnimatorStateInfo stateInfo){}
		public virtual void OnStateEnterToRun(Animator animator, AnimatorStateInfo stateInfo){}
		public virtual void OnStateExitFromRun(Animator animator, AnimatorStateInfo stateInfo){}
		public virtual void OnStateMoveRun(Animator animator, AnimatorStateInfo stateInfo){}
		public virtual void OnStateUpdateRun(Animator animator, AnimatorStateInfo stateInfo){}
		public virtual void OnStateIKRun(Animator animator, AnimatorStateInfo stateInfo){}
		public virtual void OnStateEnterToJump(Animator animator, AnimatorStateInfo stateInfo){}
		public virtual void OnStateExitFromJump(Animator animator, AnimatorStateInfo stateInfo){}
		public virtual void OnStateMoveJump(Animator animator, AnimatorStateInfo stateInfo){}
		public virtual void OnStateUpdateJump(Animator animator, AnimatorStateInfo stateInfo){}
		public virtual void OnStateIKJump(Animator animator, AnimatorStateInfo stateInfo){}
		public virtual void OnStateEnterToKick(Animator animator, AnimatorStateInfo stateInfo){}
		public virtual void OnStateExitFromKick(Animator animator, AnimatorStateInfo stateInfo){}
		public virtual void OnStateMoveKick(Animator animator, AnimatorStateInfo stateInfo){}
		public virtual void OnStateUpdateKick(Animator animator, AnimatorStateInfo stateInfo){}
		public virtual void OnStateIKKick(Animator animator, AnimatorStateInfo stateInfo){}
		public virtual void OnStateEnterToScrewKick(Animator animator, AnimatorStateInfo stateInfo){}
		public virtual void OnStateExitFromScrewKick(Animator animator, AnimatorStateInfo stateInfo){}
		public virtual void OnStateMoveScrewKick(Animator animator, AnimatorStateInfo stateInfo){}
		public virtual void OnStateUpdateScrewKick(Animator animator, AnimatorStateInfo stateInfo){}
		public virtual void OnStateIKScrewKick(Animator animator, AnimatorStateInfo stateInfo){}



		public override void OnStateEnter(Animator animator, AnimatorStateInfo stateInfo, int layerIndex)
		{
			//新しいステートに移り変わった時に実行
			switch(layerIndex)
			{
				// case 
				case StateIdAttack_Fire1 : OnStateEnterToAttack_Fire1(animator, stateInfo); break;
				case StateIdIdle : OnStateEnterToIdle(animator, stateInfo); break;
				case StateIdRun : OnStateEnterToRun(animator, stateInfo); break;
				case StateIdJump : OnStateEnterToJump(animator, stateInfo); break;
				case StateIdKick : OnStateEnterToKick(animator, stateInfo); break;
				case StateIdScrewKick : OnStateEnterToScrewKick(animator, stateInfo); break;

			}
		}

		public override void OnStateExit(Animator animator, AnimatorStateInfo stateInfo, int layerIndex)
		{
			//ステートが次のステートに移り変わる直前に実行
			switch(layerIndex)
			{
				// case 
				case StateIdAttack_Fire1 : OnStateExitFromAttack_Fire1(animator, stateInfo); break;
				case StateIdIdle : OnStateExitFromIdle(animator, stateInfo); break;
				case StateIdRun : OnStateExitFromRun(animator, stateInfo); break;
				case StateIdJump : OnStateExitFromJump(animator, stateInfo); break;
				case StateIdKick : OnStateExitFromKick(animator, stateInfo); break;
				case StateIdScrewKick : OnStateExitFromScrewKick(animator, stateInfo); break;

			}
		}

		public override void OnStateMachineEnter(Animator animator, int stateMachinePathHash)
		{
			//スクリプトが貼り付けられたステートマシンに遷移してきた時に実行
			
		}

		public override void OnStateMachineExit(Animator animator, int stateMachinePathHash)
		{
			//スクリプトが貼り付けられたステートマシンから出て行く時に実行			
			
		}

		public override void OnStateMove(Animator animator, AnimatorStateInfo stateInfo, int layerIndex)
		{
			//MonoBehaviour.OnAnimatorMoveの直後に実行される
			switch(layerIndex)
			{
				// case 
				case StateIdAttack_Fire1 : OnStateMoveAttack_Fire1(animator, stateInfo); break;
				case StateIdIdle : OnStateMoveIdle(animator, stateInfo); break;
				case StateIdRun : OnStateMoveRun(animator, stateInfo); break;
				case StateIdJump : OnStateMoveJump(animator, stateInfo); break;
				case StateIdKick : OnStateMoveKick(animator, stateInfo); break;
				case StateIdScrewKick : OnStateMoveScrewKick(animator, stateInfo); break;

			}
		}

		public override void OnStateUpdate(Animator animator, AnimatorStateInfo stateInfo, int layerIndex)
		{
			switch(layerIndex)
			{
				// case 
				case StateIdAttack_Fire1 : OnStateUpdateAttack_Fire1(animator, stateInfo); break;
				case StateIdIdle : OnStateUpdateIdle(animator, stateInfo); break;
				case StateIdRun : OnStateUpdateRun(animator, stateInfo); break;
				case StateIdJump : OnStateUpdateJump(animator, stateInfo); break;
				case StateIdKick : OnStateUpdateKick(animator, stateInfo); break;
				case StateIdScrewKick : OnStateUpdateScrewKick(animator, stateInfo); break;

			}
		}

		public override void OnStateIK(Animator animator, AnimatorStateInfo stateInfo, int layerIndex)
		{
			//MonoBehaviour.OnAnimatorIKの直後に実行される
			switch(layerIndex)
			{
				// case 
				case StateIdAttack_Fire1 : OnStateIKAttack_Fire1(animator, stateInfo); break;
				case StateIdIdle : OnStateIKIdle(animator, stateInfo); break;
				case StateIdRun : OnStateIKRun(animator, stateInfo); break;
				case StateIdJump : OnStateIKJump(animator, stateInfo); break;
				case StateIdKick : OnStateIKKick(animator, stateInfo); break;
				case StateIdScrewKick : OnStateIKScrewKick(animator, stateInfo); break;

			}
		}
	}
}