using System;
using UnityEngine;
// generated by Editor/AnimatorAccess ☀
namespace AnimatorAccess
{
	[System.Serializable]
	public class UnityChanARPose : StateMachineBehaviour
	{
		protected Animator _animator;

		public void SetAnimator(Animator animator){ _animator = animator; }

		// Perameters
		// hash values
		protected const int NextHash = -1541554430;
		protected const int BackHash = -839094775;

		// parameter setter getter 
		public bool GetNext(){ return _animator.GetBool(NextHash); }
		public void SetNext(bool value){ _animator.SetBool(NextHash, value);}
		public bool GetBack(){ return _animator.GetBool(BackHash); }
		public void SetBack(bool value){ _animator.SetBool(BackHash, value);}

		// State
		public const int StateIdPOSE01 = 1168970017;
		public const int StateIdPOSE02 = -593215333;
		public const int StateIdPOSE03 = -1415352307;
		public const int StateIdPOSE04 = 902292910;
		public const int StateIdPOSE05 = 1119933752;
		public const int StateIdPOSE06 = -607550334;
		public const int StateIdPOSE07 = -1395739628;
		public const int StateIdPOSE08 = 1014081925;
		public const int StateIdPOSE09 = 1266063635;
		public const int StateIdPOSE10 = 733024502;
		public const int StateIdPOSE11 = 1555439712;
		public const int StateIdPOSE12 = -977309222;
		public const int StateIdPOSE13 = -1296547508;
		public const int StateIdPOSE14 = 752669935;
		public const int StateIdPOSE15 = 1541137529;
		public const int StateIdPOSE16 = -1026378301;
		public const int StateIdPOSE17 = -1244297899;
		public const int StateIdPOSE18 = 627742916;
		public const int StateIdPOSE19 = 1382918226;
		public const int StateIdPOSE20 = 10240821;
		public const int StateIdPOSE21 = 2006676387;
		public const int StateIdPOSE22 = -292412903;
		public const int StateIdPOSE23 = -1718283633;
		public const int StateIdPOSE24 = 133269292;
		public const int StateIdPOSE25 = 1895217082;
		public const int StateIdPOSE26 = -369105408;
		public const int StateIdPOSE27 = -1627859306;
		public const int StateIdPOSE28 = 239586055;
		public const int StateIdPOSE29 = 2034301841;
		public const int StateIdPOSE30 = 428307060;
		public const int StateIdPOSE31 = 1853899490;
		public const int StateIdFace_angry1_unitychan = -737699690;
		public const int StateIdFace_sap_unitychan = 679883102;
		public const int StateIdFace_conf_unitychan = -2036183103;
		public const int StateIdFace_smile2_unitychan = -1317547900;
		public const int StateIdFace_eye_close_unitychan = 385519305;
		public const int StateIdFace_smile1_unitychan = 680900229;
		public const int StateIdFace_angry2_unitychan = 1306918551;
		public const int StateIdFace_default_unitychan = -1456140119;
		public const int StateIdFace_default_unitychan0 = -1862879232;
		public const int StateIdFace_disstract1_unitychan = 2006997602;
		public const int StateIdFace_disstract2_unitychan = -297649053;

		public bool IsPOSE01State(){ return StateIdPOSE01 == _animator.GetCurrentAnimatorStateInfo(0).fullPathHash; }
		public bool IsPOSE02State(){ return StateIdPOSE02 == _animator.GetCurrentAnimatorStateInfo(0).fullPathHash; }
		public bool IsPOSE03State(){ return StateIdPOSE03 == _animator.GetCurrentAnimatorStateInfo(0).fullPathHash; }
		public bool IsPOSE04State(){ return StateIdPOSE04 == _animator.GetCurrentAnimatorStateInfo(0).fullPathHash; }
		public bool IsPOSE05State(){ return StateIdPOSE05 == _animator.GetCurrentAnimatorStateInfo(0).fullPathHash; }
		public bool IsPOSE06State(){ return StateIdPOSE06 == _animator.GetCurrentAnimatorStateInfo(0).fullPathHash; }
		public bool IsPOSE07State(){ return StateIdPOSE07 == _animator.GetCurrentAnimatorStateInfo(0).fullPathHash; }
		public bool IsPOSE08State(){ return StateIdPOSE08 == _animator.GetCurrentAnimatorStateInfo(0).fullPathHash; }
		public bool IsPOSE09State(){ return StateIdPOSE09 == _animator.GetCurrentAnimatorStateInfo(0).fullPathHash; }
		public bool IsPOSE10State(){ return StateIdPOSE10 == _animator.GetCurrentAnimatorStateInfo(0).fullPathHash; }
		public bool IsPOSE11State(){ return StateIdPOSE11 == _animator.GetCurrentAnimatorStateInfo(0).fullPathHash; }
		public bool IsPOSE12State(){ return StateIdPOSE12 == _animator.GetCurrentAnimatorStateInfo(0).fullPathHash; }
		public bool IsPOSE13State(){ return StateIdPOSE13 == _animator.GetCurrentAnimatorStateInfo(0).fullPathHash; }
		public bool IsPOSE14State(){ return StateIdPOSE14 == _animator.GetCurrentAnimatorStateInfo(0).fullPathHash; }
		public bool IsPOSE15State(){ return StateIdPOSE15 == _animator.GetCurrentAnimatorStateInfo(0).fullPathHash; }
		public bool IsPOSE16State(){ return StateIdPOSE16 == _animator.GetCurrentAnimatorStateInfo(0).fullPathHash; }
		public bool IsPOSE17State(){ return StateIdPOSE17 == _animator.GetCurrentAnimatorStateInfo(0).fullPathHash; }
		public bool IsPOSE18State(){ return StateIdPOSE18 == _animator.GetCurrentAnimatorStateInfo(0).fullPathHash; }
		public bool IsPOSE19State(){ return StateIdPOSE19 == _animator.GetCurrentAnimatorStateInfo(0).fullPathHash; }
		public bool IsPOSE20State(){ return StateIdPOSE20 == _animator.GetCurrentAnimatorStateInfo(0).fullPathHash; }
		public bool IsPOSE21State(){ return StateIdPOSE21 == _animator.GetCurrentAnimatorStateInfo(0).fullPathHash; }
		public bool IsPOSE22State(){ return StateIdPOSE22 == _animator.GetCurrentAnimatorStateInfo(0).fullPathHash; }
		public bool IsPOSE23State(){ return StateIdPOSE23 == _animator.GetCurrentAnimatorStateInfo(0).fullPathHash; }
		public bool IsPOSE24State(){ return StateIdPOSE24 == _animator.GetCurrentAnimatorStateInfo(0).fullPathHash; }
		public bool IsPOSE25State(){ return StateIdPOSE25 == _animator.GetCurrentAnimatorStateInfo(0).fullPathHash; }
		public bool IsPOSE26State(){ return StateIdPOSE26 == _animator.GetCurrentAnimatorStateInfo(0).fullPathHash; }
		public bool IsPOSE27State(){ return StateIdPOSE27 == _animator.GetCurrentAnimatorStateInfo(0).fullPathHash; }
		public bool IsPOSE28State(){ return StateIdPOSE28 == _animator.GetCurrentAnimatorStateInfo(0).fullPathHash; }
		public bool IsPOSE29State(){ return StateIdPOSE29 == _animator.GetCurrentAnimatorStateInfo(0).fullPathHash; }
		public bool IsPOSE30State(){ return StateIdPOSE30 == _animator.GetCurrentAnimatorStateInfo(0).fullPathHash; }
		public bool IsPOSE31State(){ return StateIdPOSE31 == _animator.GetCurrentAnimatorStateInfo(0).fullPathHash; }
		public bool IsFace_angry1_unitychanState(){ return StateIdFace_angry1_unitychan == _animator.GetCurrentAnimatorStateInfo(0).fullPathHash; }
		public bool IsFace_sap_unitychanState(){ return StateIdFace_sap_unitychan == _animator.GetCurrentAnimatorStateInfo(0).fullPathHash; }
		public bool IsFace_conf_unitychanState(){ return StateIdFace_conf_unitychan == _animator.GetCurrentAnimatorStateInfo(0).fullPathHash; }
		public bool IsFace_smile2_unitychanState(){ return StateIdFace_smile2_unitychan == _animator.GetCurrentAnimatorStateInfo(0).fullPathHash; }
		public bool IsFace_eye_close_unitychanState(){ return StateIdFace_eye_close_unitychan == _animator.GetCurrentAnimatorStateInfo(0).fullPathHash; }
		public bool IsFace_smile1_unitychanState(){ return StateIdFace_smile1_unitychan == _animator.GetCurrentAnimatorStateInfo(0).fullPathHash; }
		public bool IsFace_angry2_unitychanState(){ return StateIdFace_angry2_unitychan == _animator.GetCurrentAnimatorStateInfo(0).fullPathHash; }
		public bool IsFace_default_unitychanState(){ return StateIdFace_default_unitychan == _animator.GetCurrentAnimatorStateInfo(0).fullPathHash; }
		public bool IsFace_default_unitychan0State(){ return StateIdFace_default_unitychan0 == _animator.GetCurrentAnimatorStateInfo(0).fullPathHash; }
		public bool IsFace_disstract1_unitychanState(){ return StateIdFace_disstract1_unitychan == _animator.GetCurrentAnimatorStateInfo(0).fullPathHash; }
		public bool IsFace_disstract2_unitychanState(){ return StateIdFace_disstract2_unitychan == _animator.GetCurrentAnimatorStateInfo(0).fullPathHash; }

		public virtual void OnStateEnterToPOSE01(Animator animator, AnimatorStateInfo stateInfo){}
		public virtual void OnStateExitFromPOSE01(Animator animator, AnimatorStateInfo stateInfo){}
//		public virtual void OnStateMovePOSE01(Animator animator, AnimatorStateInfo stateInfo){}
		public virtual void OnStateUpdatePOSE01(Animator animator, AnimatorStateInfo stateInfo){}
		public virtual void OnStateIkPOSE01(Animator animator, AnimatorStateInfo stateInfo){}
		public virtual void OnStateEnterToPOSE02(Animator animator, AnimatorStateInfo stateInfo){}
		public virtual void OnStateExitFromPOSE02(Animator animator, AnimatorStateInfo stateInfo){}
//		public virtual void OnStateMovePOSE02(Animator animator, AnimatorStateInfo stateInfo){}
		public virtual void OnStateUpdatePOSE02(Animator animator, AnimatorStateInfo stateInfo){}
		public virtual void OnStateIkPOSE02(Animator animator, AnimatorStateInfo stateInfo){}
		public virtual void OnStateEnterToPOSE03(Animator animator, AnimatorStateInfo stateInfo){}
		public virtual void OnStateExitFromPOSE03(Animator animator, AnimatorStateInfo stateInfo){}
//		public virtual void OnStateMovePOSE03(Animator animator, AnimatorStateInfo stateInfo){}
		public virtual void OnStateUpdatePOSE03(Animator animator, AnimatorStateInfo stateInfo){}
		public virtual void OnStateIkPOSE03(Animator animator, AnimatorStateInfo stateInfo){}
		public virtual void OnStateEnterToPOSE04(Animator animator, AnimatorStateInfo stateInfo){}
		public virtual void OnStateExitFromPOSE04(Animator animator, AnimatorStateInfo stateInfo){}
//		public virtual void OnStateMovePOSE04(Animator animator, AnimatorStateInfo stateInfo){}
		public virtual void OnStateUpdatePOSE04(Animator animator, AnimatorStateInfo stateInfo){}
		public virtual void OnStateIkPOSE04(Animator animator, AnimatorStateInfo stateInfo){}
		public virtual void OnStateEnterToPOSE05(Animator animator, AnimatorStateInfo stateInfo){}
		public virtual void OnStateExitFromPOSE05(Animator animator, AnimatorStateInfo stateInfo){}
//		public virtual void OnStateMovePOSE05(Animator animator, AnimatorStateInfo stateInfo){}
		public virtual void OnStateUpdatePOSE05(Animator animator, AnimatorStateInfo stateInfo){}
		public virtual void OnStateIkPOSE05(Animator animator, AnimatorStateInfo stateInfo){}
		public virtual void OnStateEnterToPOSE06(Animator animator, AnimatorStateInfo stateInfo){}
		public virtual void OnStateExitFromPOSE06(Animator animator, AnimatorStateInfo stateInfo){}
//		public virtual void OnStateMovePOSE06(Animator animator, AnimatorStateInfo stateInfo){}
		public virtual void OnStateUpdatePOSE06(Animator animator, AnimatorStateInfo stateInfo){}
		public virtual void OnStateIkPOSE06(Animator animator, AnimatorStateInfo stateInfo){}
		public virtual void OnStateEnterToPOSE07(Animator animator, AnimatorStateInfo stateInfo){}
		public virtual void OnStateExitFromPOSE07(Animator animator, AnimatorStateInfo stateInfo){}
//		public virtual void OnStateMovePOSE07(Animator animator, AnimatorStateInfo stateInfo){}
		public virtual void OnStateUpdatePOSE07(Animator animator, AnimatorStateInfo stateInfo){}
		public virtual void OnStateIkPOSE07(Animator animator, AnimatorStateInfo stateInfo){}
		public virtual void OnStateEnterToPOSE08(Animator animator, AnimatorStateInfo stateInfo){}
		public virtual void OnStateExitFromPOSE08(Animator animator, AnimatorStateInfo stateInfo){}
//		public virtual void OnStateMovePOSE08(Animator animator, AnimatorStateInfo stateInfo){}
		public virtual void OnStateUpdatePOSE08(Animator animator, AnimatorStateInfo stateInfo){}
		public virtual void OnStateIkPOSE08(Animator animator, AnimatorStateInfo stateInfo){}
		public virtual void OnStateEnterToPOSE09(Animator animator, AnimatorStateInfo stateInfo){}
		public virtual void OnStateExitFromPOSE09(Animator animator, AnimatorStateInfo stateInfo){}
//		public virtual void OnStateMovePOSE09(Animator animator, AnimatorStateInfo stateInfo){}
		public virtual void OnStateUpdatePOSE09(Animator animator, AnimatorStateInfo stateInfo){}
		public virtual void OnStateIkPOSE09(Animator animator, AnimatorStateInfo stateInfo){}
		public virtual void OnStateEnterToPOSE10(Animator animator, AnimatorStateInfo stateInfo){}
		public virtual void OnStateExitFromPOSE10(Animator animator, AnimatorStateInfo stateInfo){}
//		public virtual void OnStateMovePOSE10(Animator animator, AnimatorStateInfo stateInfo){}
		public virtual void OnStateUpdatePOSE10(Animator animator, AnimatorStateInfo stateInfo){}
		public virtual void OnStateIkPOSE10(Animator animator, AnimatorStateInfo stateInfo){}
		public virtual void OnStateEnterToPOSE11(Animator animator, AnimatorStateInfo stateInfo){}
		public virtual void OnStateExitFromPOSE11(Animator animator, AnimatorStateInfo stateInfo){}
//		public virtual void OnStateMovePOSE11(Animator animator, AnimatorStateInfo stateInfo){}
		public virtual void OnStateUpdatePOSE11(Animator animator, AnimatorStateInfo stateInfo){}
		public virtual void OnStateIkPOSE11(Animator animator, AnimatorStateInfo stateInfo){}
		public virtual void OnStateEnterToPOSE12(Animator animator, AnimatorStateInfo stateInfo){}
		public virtual void OnStateExitFromPOSE12(Animator animator, AnimatorStateInfo stateInfo){}
//		public virtual void OnStateMovePOSE12(Animator animator, AnimatorStateInfo stateInfo){}
		public virtual void OnStateUpdatePOSE12(Animator animator, AnimatorStateInfo stateInfo){}
		public virtual void OnStateIkPOSE12(Animator animator, AnimatorStateInfo stateInfo){}
		public virtual void OnStateEnterToPOSE13(Animator animator, AnimatorStateInfo stateInfo){}
		public virtual void OnStateExitFromPOSE13(Animator animator, AnimatorStateInfo stateInfo){}
//		public virtual void OnStateMovePOSE13(Animator animator, AnimatorStateInfo stateInfo){}
		public virtual void OnStateUpdatePOSE13(Animator animator, AnimatorStateInfo stateInfo){}
		public virtual void OnStateIkPOSE13(Animator animator, AnimatorStateInfo stateInfo){}
		public virtual void OnStateEnterToPOSE14(Animator animator, AnimatorStateInfo stateInfo){}
		public virtual void OnStateExitFromPOSE14(Animator animator, AnimatorStateInfo stateInfo){}
//		public virtual void OnStateMovePOSE14(Animator animator, AnimatorStateInfo stateInfo){}
		public virtual void OnStateUpdatePOSE14(Animator animator, AnimatorStateInfo stateInfo){}
		public virtual void OnStateIkPOSE14(Animator animator, AnimatorStateInfo stateInfo){}
		public virtual void OnStateEnterToPOSE15(Animator animator, AnimatorStateInfo stateInfo){}
		public virtual void OnStateExitFromPOSE15(Animator animator, AnimatorStateInfo stateInfo){}
//		public virtual void OnStateMovePOSE15(Animator animator, AnimatorStateInfo stateInfo){}
		public virtual void OnStateUpdatePOSE15(Animator animator, AnimatorStateInfo stateInfo){}
		public virtual void OnStateIkPOSE15(Animator animator, AnimatorStateInfo stateInfo){}
		public virtual void OnStateEnterToPOSE16(Animator animator, AnimatorStateInfo stateInfo){}
		public virtual void OnStateExitFromPOSE16(Animator animator, AnimatorStateInfo stateInfo){}
//		public virtual void OnStateMovePOSE16(Animator animator, AnimatorStateInfo stateInfo){}
		public virtual void OnStateUpdatePOSE16(Animator animator, AnimatorStateInfo stateInfo){}
		public virtual void OnStateIkPOSE16(Animator animator, AnimatorStateInfo stateInfo){}
		public virtual void OnStateEnterToPOSE17(Animator animator, AnimatorStateInfo stateInfo){}
		public virtual void OnStateExitFromPOSE17(Animator animator, AnimatorStateInfo stateInfo){}
//		public virtual void OnStateMovePOSE17(Animator animator, AnimatorStateInfo stateInfo){}
		public virtual void OnStateUpdatePOSE17(Animator animator, AnimatorStateInfo stateInfo){}
		public virtual void OnStateIkPOSE17(Animator animator, AnimatorStateInfo stateInfo){}
		public virtual void OnStateEnterToPOSE18(Animator animator, AnimatorStateInfo stateInfo){}
		public virtual void OnStateExitFromPOSE18(Animator animator, AnimatorStateInfo stateInfo){}
//		public virtual void OnStateMovePOSE18(Animator animator, AnimatorStateInfo stateInfo){}
		public virtual void OnStateUpdatePOSE18(Animator animator, AnimatorStateInfo stateInfo){}
		public virtual void OnStateIkPOSE18(Animator animator, AnimatorStateInfo stateInfo){}
		public virtual void OnStateEnterToPOSE19(Animator animator, AnimatorStateInfo stateInfo){}
		public virtual void OnStateExitFromPOSE19(Animator animator, AnimatorStateInfo stateInfo){}
//		public virtual void OnStateMovePOSE19(Animator animator, AnimatorStateInfo stateInfo){}
		public virtual void OnStateUpdatePOSE19(Animator animator, AnimatorStateInfo stateInfo){}
		public virtual void OnStateIkPOSE19(Animator animator, AnimatorStateInfo stateInfo){}
		public virtual void OnStateEnterToPOSE20(Animator animator, AnimatorStateInfo stateInfo){}
		public virtual void OnStateExitFromPOSE20(Animator animator, AnimatorStateInfo stateInfo){}
//		public virtual void OnStateMovePOSE20(Animator animator, AnimatorStateInfo stateInfo){}
		public virtual void OnStateUpdatePOSE20(Animator animator, AnimatorStateInfo stateInfo){}
		public virtual void OnStateIkPOSE20(Animator animator, AnimatorStateInfo stateInfo){}
		public virtual void OnStateEnterToPOSE21(Animator animator, AnimatorStateInfo stateInfo){}
		public virtual void OnStateExitFromPOSE21(Animator animator, AnimatorStateInfo stateInfo){}
//		public virtual void OnStateMovePOSE21(Animator animator, AnimatorStateInfo stateInfo){}
		public virtual void OnStateUpdatePOSE21(Animator animator, AnimatorStateInfo stateInfo){}
		public virtual void OnStateIkPOSE21(Animator animator, AnimatorStateInfo stateInfo){}
		public virtual void OnStateEnterToPOSE22(Animator animator, AnimatorStateInfo stateInfo){}
		public virtual void OnStateExitFromPOSE22(Animator animator, AnimatorStateInfo stateInfo){}
//		public virtual void OnStateMovePOSE22(Animator animator, AnimatorStateInfo stateInfo){}
		public virtual void OnStateUpdatePOSE22(Animator animator, AnimatorStateInfo stateInfo){}
		public virtual void OnStateIkPOSE22(Animator animator, AnimatorStateInfo stateInfo){}
		public virtual void OnStateEnterToPOSE23(Animator animator, AnimatorStateInfo stateInfo){}
		public virtual void OnStateExitFromPOSE23(Animator animator, AnimatorStateInfo stateInfo){}
//		public virtual void OnStateMovePOSE23(Animator animator, AnimatorStateInfo stateInfo){}
		public virtual void OnStateUpdatePOSE23(Animator animator, AnimatorStateInfo stateInfo){}
		public virtual void OnStateIkPOSE23(Animator animator, AnimatorStateInfo stateInfo){}
		public virtual void OnStateEnterToPOSE24(Animator animator, AnimatorStateInfo stateInfo){}
		public virtual void OnStateExitFromPOSE24(Animator animator, AnimatorStateInfo stateInfo){}
//		public virtual void OnStateMovePOSE24(Animator animator, AnimatorStateInfo stateInfo){}
		public virtual void OnStateUpdatePOSE24(Animator animator, AnimatorStateInfo stateInfo){}
		public virtual void OnStateIkPOSE24(Animator animator, AnimatorStateInfo stateInfo){}
		public virtual void OnStateEnterToPOSE25(Animator animator, AnimatorStateInfo stateInfo){}
		public virtual void OnStateExitFromPOSE25(Animator animator, AnimatorStateInfo stateInfo){}
//		public virtual void OnStateMovePOSE25(Animator animator, AnimatorStateInfo stateInfo){}
		public virtual void OnStateUpdatePOSE25(Animator animator, AnimatorStateInfo stateInfo){}
		public virtual void OnStateIkPOSE25(Animator animator, AnimatorStateInfo stateInfo){}
		public virtual void OnStateEnterToPOSE26(Animator animator, AnimatorStateInfo stateInfo){}
		public virtual void OnStateExitFromPOSE26(Animator animator, AnimatorStateInfo stateInfo){}
//		public virtual void OnStateMovePOSE26(Animator animator, AnimatorStateInfo stateInfo){}
		public virtual void OnStateUpdatePOSE26(Animator animator, AnimatorStateInfo stateInfo){}
		public virtual void OnStateIkPOSE26(Animator animator, AnimatorStateInfo stateInfo){}
		public virtual void OnStateEnterToPOSE27(Animator animator, AnimatorStateInfo stateInfo){}
		public virtual void OnStateExitFromPOSE27(Animator animator, AnimatorStateInfo stateInfo){}
//		public virtual void OnStateMovePOSE27(Animator animator, AnimatorStateInfo stateInfo){}
		public virtual void OnStateUpdatePOSE27(Animator animator, AnimatorStateInfo stateInfo){}
		public virtual void OnStateIkPOSE27(Animator animator, AnimatorStateInfo stateInfo){}
		public virtual void OnStateEnterToPOSE28(Animator animator, AnimatorStateInfo stateInfo){}
		public virtual void OnStateExitFromPOSE28(Animator animator, AnimatorStateInfo stateInfo){}
//		public virtual void OnStateMovePOSE28(Animator animator, AnimatorStateInfo stateInfo){}
		public virtual void OnStateUpdatePOSE28(Animator animator, AnimatorStateInfo stateInfo){}
		public virtual void OnStateIkPOSE28(Animator animator, AnimatorStateInfo stateInfo){}
		public virtual void OnStateEnterToPOSE29(Animator animator, AnimatorStateInfo stateInfo){}
		public virtual void OnStateExitFromPOSE29(Animator animator, AnimatorStateInfo stateInfo){}
//		public virtual void OnStateMovePOSE29(Animator animator, AnimatorStateInfo stateInfo){}
		public virtual void OnStateUpdatePOSE29(Animator animator, AnimatorStateInfo stateInfo){}
		public virtual void OnStateIkPOSE29(Animator animator, AnimatorStateInfo stateInfo){}
		public virtual void OnStateEnterToPOSE30(Animator animator, AnimatorStateInfo stateInfo){}
		public virtual void OnStateExitFromPOSE30(Animator animator, AnimatorStateInfo stateInfo){}
//		public virtual void OnStateMovePOSE30(Animator animator, AnimatorStateInfo stateInfo){}
		public virtual void OnStateUpdatePOSE30(Animator animator, AnimatorStateInfo stateInfo){}
		public virtual void OnStateIkPOSE30(Animator animator, AnimatorStateInfo stateInfo){}
		public virtual void OnStateEnterToPOSE31(Animator animator, AnimatorStateInfo stateInfo){}
		public virtual void OnStateExitFromPOSE31(Animator animator, AnimatorStateInfo stateInfo){}
//		public virtual void OnStateMovePOSE31(Animator animator, AnimatorStateInfo stateInfo){}
		public virtual void OnStateUpdatePOSE31(Animator animator, AnimatorStateInfo stateInfo){}
		public virtual void OnStateIkPOSE31(Animator animator, AnimatorStateInfo stateInfo){}
		public virtual void OnStateEnterToFace_angry1_unitychan(Animator animator, AnimatorStateInfo stateInfo){}
		public virtual void OnStateExitFromFace_angry1_unitychan(Animator animator, AnimatorStateInfo stateInfo){}
//		public virtual void OnStateMoveFace_angry1_unitychan(Animator animator, AnimatorStateInfo stateInfo){}
		public virtual void OnStateUpdateFace_angry1_unitychan(Animator animator, AnimatorStateInfo stateInfo){}
		public virtual void OnStateIkFace_angry1_unitychan(Animator animator, AnimatorStateInfo stateInfo){}
		public virtual void OnStateEnterToFace_sap_unitychan(Animator animator, AnimatorStateInfo stateInfo){}
		public virtual void OnStateExitFromFace_sap_unitychan(Animator animator, AnimatorStateInfo stateInfo){}
//		public virtual void OnStateMoveFace_sap_unitychan(Animator animator, AnimatorStateInfo stateInfo){}
		public virtual void OnStateUpdateFace_sap_unitychan(Animator animator, AnimatorStateInfo stateInfo){}
		public virtual void OnStateIkFace_sap_unitychan(Animator animator, AnimatorStateInfo stateInfo){}
		public virtual void OnStateEnterToFace_conf_unitychan(Animator animator, AnimatorStateInfo stateInfo){}
		public virtual void OnStateExitFromFace_conf_unitychan(Animator animator, AnimatorStateInfo stateInfo){}
//		public virtual void OnStateMoveFace_conf_unitychan(Animator animator, AnimatorStateInfo stateInfo){}
		public virtual void OnStateUpdateFace_conf_unitychan(Animator animator, AnimatorStateInfo stateInfo){}
		public virtual void OnStateIkFace_conf_unitychan(Animator animator, AnimatorStateInfo stateInfo){}
		public virtual void OnStateEnterToFace_smile2_unitychan(Animator animator, AnimatorStateInfo stateInfo){}
		public virtual void OnStateExitFromFace_smile2_unitychan(Animator animator, AnimatorStateInfo stateInfo){}
//		public virtual void OnStateMoveFace_smile2_unitychan(Animator animator, AnimatorStateInfo stateInfo){}
		public virtual void OnStateUpdateFace_smile2_unitychan(Animator animator, AnimatorStateInfo stateInfo){}
		public virtual void OnStateIkFace_smile2_unitychan(Animator animator, AnimatorStateInfo stateInfo){}
		public virtual void OnStateEnterToFace_eye_close_unitychan(Animator animator, AnimatorStateInfo stateInfo){}
		public virtual void OnStateExitFromFace_eye_close_unitychan(Animator animator, AnimatorStateInfo stateInfo){}
//		public virtual void OnStateMoveFace_eye_close_unitychan(Animator animator, AnimatorStateInfo stateInfo){}
		public virtual void OnStateUpdateFace_eye_close_unitychan(Animator animator, AnimatorStateInfo stateInfo){}
		public virtual void OnStateIkFace_eye_close_unitychan(Animator animator, AnimatorStateInfo stateInfo){}
		public virtual void OnStateEnterToFace_smile1_unitychan(Animator animator, AnimatorStateInfo stateInfo){}
		public virtual void OnStateExitFromFace_smile1_unitychan(Animator animator, AnimatorStateInfo stateInfo){}
//		public virtual void OnStateMoveFace_smile1_unitychan(Animator animator, AnimatorStateInfo stateInfo){}
		public virtual void OnStateUpdateFace_smile1_unitychan(Animator animator, AnimatorStateInfo stateInfo){}
		public virtual void OnStateIkFace_smile1_unitychan(Animator animator, AnimatorStateInfo stateInfo){}
		public virtual void OnStateEnterToFace_angry2_unitychan(Animator animator, AnimatorStateInfo stateInfo){}
		public virtual void OnStateExitFromFace_angry2_unitychan(Animator animator, AnimatorStateInfo stateInfo){}
//		public virtual void OnStateMoveFace_angry2_unitychan(Animator animator, AnimatorStateInfo stateInfo){}
		public virtual void OnStateUpdateFace_angry2_unitychan(Animator animator, AnimatorStateInfo stateInfo){}
		public virtual void OnStateIkFace_angry2_unitychan(Animator animator, AnimatorStateInfo stateInfo){}
		public virtual void OnStateEnterToFace_default_unitychan(Animator animator, AnimatorStateInfo stateInfo){}
		public virtual void OnStateExitFromFace_default_unitychan(Animator animator, AnimatorStateInfo stateInfo){}
//		public virtual void OnStateMoveFace_default_unitychan(Animator animator, AnimatorStateInfo stateInfo){}
		public virtual void OnStateUpdateFace_default_unitychan(Animator animator, AnimatorStateInfo stateInfo){}
		public virtual void OnStateIkFace_default_unitychan(Animator animator, AnimatorStateInfo stateInfo){}
		public virtual void OnStateEnterToFace_default_unitychan0(Animator animator, AnimatorStateInfo stateInfo){}
		public virtual void OnStateExitFromFace_default_unitychan0(Animator animator, AnimatorStateInfo stateInfo){}
//		public virtual void OnStateMoveFace_default_unitychan0(Animator animator, AnimatorStateInfo stateInfo){}
		public virtual void OnStateUpdateFace_default_unitychan0(Animator animator, AnimatorStateInfo stateInfo){}
		public virtual void OnStateIkFace_default_unitychan0(Animator animator, AnimatorStateInfo stateInfo){}
		public virtual void OnStateEnterToFace_disstract1_unitychan(Animator animator, AnimatorStateInfo stateInfo){}
		public virtual void OnStateExitFromFace_disstract1_unitychan(Animator animator, AnimatorStateInfo stateInfo){}
//		public virtual void OnStateMoveFace_disstract1_unitychan(Animator animator, AnimatorStateInfo stateInfo){}
		public virtual void OnStateUpdateFace_disstract1_unitychan(Animator animator, AnimatorStateInfo stateInfo){}
		public virtual void OnStateIkFace_disstract1_unitychan(Animator animator, AnimatorStateInfo stateInfo){}
		public virtual void OnStateEnterToFace_disstract2_unitychan(Animator animator, AnimatorStateInfo stateInfo){}
		public virtual void OnStateExitFromFace_disstract2_unitychan(Animator animator, AnimatorStateInfo stateInfo){}
//		public virtual void OnStateMoveFace_disstract2_unitychan(Animator animator, AnimatorStateInfo stateInfo){}
		public virtual void OnStateUpdateFace_disstract2_unitychan(Animator animator, AnimatorStateInfo stateInfo){}
		public virtual void OnStateIkFace_disstract2_unitychan(Animator animator, AnimatorStateInfo stateInfo){}



		public override void OnStateEnter(Animator animator, AnimatorStateInfo stateInfo, int layerIndex)
		{
			//新しいステートに移り変わった時に実行
			switch(layerIndex)
			{
				// case 
				case StateIdPOSE01 : OnStateEnterToPOSE01(animator, stateInfo); break;
				case StateIdPOSE02 : OnStateEnterToPOSE02(animator, stateInfo); break;
				case StateIdPOSE03 : OnStateEnterToPOSE03(animator, stateInfo); break;
				case StateIdPOSE04 : OnStateEnterToPOSE04(animator, stateInfo); break;
				case StateIdPOSE05 : OnStateEnterToPOSE05(animator, stateInfo); break;
				case StateIdPOSE06 : OnStateEnterToPOSE06(animator, stateInfo); break;
				case StateIdPOSE07 : OnStateEnterToPOSE07(animator, stateInfo); break;
				case StateIdPOSE08 : OnStateEnterToPOSE08(animator, stateInfo); break;
				case StateIdPOSE09 : OnStateEnterToPOSE09(animator, stateInfo); break;
				case StateIdPOSE10 : OnStateEnterToPOSE10(animator, stateInfo); break;
				case StateIdPOSE11 : OnStateEnterToPOSE11(animator, stateInfo); break;
				case StateIdPOSE12 : OnStateEnterToPOSE12(animator, stateInfo); break;
				case StateIdPOSE13 : OnStateEnterToPOSE13(animator, stateInfo); break;
				case StateIdPOSE14 : OnStateEnterToPOSE14(animator, stateInfo); break;
				case StateIdPOSE15 : OnStateEnterToPOSE15(animator, stateInfo); break;
				case StateIdPOSE16 : OnStateEnterToPOSE16(animator, stateInfo); break;
				case StateIdPOSE17 : OnStateEnterToPOSE17(animator, stateInfo); break;
				case StateIdPOSE18 : OnStateEnterToPOSE18(animator, stateInfo); break;
				case StateIdPOSE19 : OnStateEnterToPOSE19(animator, stateInfo); break;
				case StateIdPOSE20 : OnStateEnterToPOSE20(animator, stateInfo); break;
				case StateIdPOSE21 : OnStateEnterToPOSE21(animator, stateInfo); break;
				case StateIdPOSE22 : OnStateEnterToPOSE22(animator, stateInfo); break;
				case StateIdPOSE23 : OnStateEnterToPOSE23(animator, stateInfo); break;
				case StateIdPOSE24 : OnStateEnterToPOSE24(animator, stateInfo); break;
				case StateIdPOSE25 : OnStateEnterToPOSE25(animator, stateInfo); break;
				case StateIdPOSE26 : OnStateEnterToPOSE26(animator, stateInfo); break;
				case StateIdPOSE27 : OnStateEnterToPOSE27(animator, stateInfo); break;
				case StateIdPOSE28 : OnStateEnterToPOSE28(animator, stateInfo); break;
				case StateIdPOSE29 : OnStateEnterToPOSE29(animator, stateInfo); break;
				case StateIdPOSE30 : OnStateEnterToPOSE30(animator, stateInfo); break;
				case StateIdPOSE31 : OnStateEnterToPOSE31(animator, stateInfo); break;
				case StateIdFace_angry1_unitychan : OnStateEnterToFace_angry1_unitychan(animator, stateInfo); break;
				case StateIdFace_sap_unitychan : OnStateEnterToFace_sap_unitychan(animator, stateInfo); break;
				case StateIdFace_conf_unitychan : OnStateEnterToFace_conf_unitychan(animator, stateInfo); break;
				case StateIdFace_smile2_unitychan : OnStateEnterToFace_smile2_unitychan(animator, stateInfo); break;
				case StateIdFace_eye_close_unitychan : OnStateEnterToFace_eye_close_unitychan(animator, stateInfo); break;
				case StateIdFace_smile1_unitychan : OnStateEnterToFace_smile1_unitychan(animator, stateInfo); break;
				case StateIdFace_angry2_unitychan : OnStateEnterToFace_angry2_unitychan(animator, stateInfo); break;
				case StateIdFace_default_unitychan : OnStateEnterToFace_default_unitychan(animator, stateInfo); break;
				case StateIdFace_default_unitychan0 : OnStateEnterToFace_default_unitychan0(animator, stateInfo); break;
				case StateIdFace_disstract1_unitychan : OnStateEnterToFace_disstract1_unitychan(animator, stateInfo); break;
				case StateIdFace_disstract2_unitychan : OnStateEnterToFace_disstract2_unitychan(animator, stateInfo); break;

			}
		}

		public override void OnStateExit(Animator animator, AnimatorStateInfo stateInfo, int layerIndex)
		{
			//ステートが次のステートに移り変わる直前に実行
			switch(layerIndex)
			{
				// case 
				case StateIdPOSE01 : OnStateExitFromPOSE01(animator, stateInfo); break;
				case StateIdPOSE02 : OnStateExitFromPOSE02(animator, stateInfo); break;
				case StateIdPOSE03 : OnStateExitFromPOSE03(animator, stateInfo); break;
				case StateIdPOSE04 : OnStateExitFromPOSE04(animator, stateInfo); break;
				case StateIdPOSE05 : OnStateExitFromPOSE05(animator, stateInfo); break;
				case StateIdPOSE06 : OnStateExitFromPOSE06(animator, stateInfo); break;
				case StateIdPOSE07 : OnStateExitFromPOSE07(animator, stateInfo); break;
				case StateIdPOSE08 : OnStateExitFromPOSE08(animator, stateInfo); break;
				case StateIdPOSE09 : OnStateExitFromPOSE09(animator, stateInfo); break;
				case StateIdPOSE10 : OnStateExitFromPOSE10(animator, stateInfo); break;
				case StateIdPOSE11 : OnStateExitFromPOSE11(animator, stateInfo); break;
				case StateIdPOSE12 : OnStateExitFromPOSE12(animator, stateInfo); break;
				case StateIdPOSE13 : OnStateExitFromPOSE13(animator, stateInfo); break;
				case StateIdPOSE14 : OnStateExitFromPOSE14(animator, stateInfo); break;
				case StateIdPOSE15 : OnStateExitFromPOSE15(animator, stateInfo); break;
				case StateIdPOSE16 : OnStateExitFromPOSE16(animator, stateInfo); break;
				case StateIdPOSE17 : OnStateExitFromPOSE17(animator, stateInfo); break;
				case StateIdPOSE18 : OnStateExitFromPOSE18(animator, stateInfo); break;
				case StateIdPOSE19 : OnStateExitFromPOSE19(animator, stateInfo); break;
				case StateIdPOSE20 : OnStateExitFromPOSE20(animator, stateInfo); break;
				case StateIdPOSE21 : OnStateExitFromPOSE21(animator, stateInfo); break;
				case StateIdPOSE22 : OnStateExitFromPOSE22(animator, stateInfo); break;
				case StateIdPOSE23 : OnStateExitFromPOSE23(animator, stateInfo); break;
				case StateIdPOSE24 : OnStateExitFromPOSE24(animator, stateInfo); break;
				case StateIdPOSE25 : OnStateExitFromPOSE25(animator, stateInfo); break;
				case StateIdPOSE26 : OnStateExitFromPOSE26(animator, stateInfo); break;
				case StateIdPOSE27 : OnStateExitFromPOSE27(animator, stateInfo); break;
				case StateIdPOSE28 : OnStateExitFromPOSE28(animator, stateInfo); break;
				case StateIdPOSE29 : OnStateExitFromPOSE29(animator, stateInfo); break;
				case StateIdPOSE30 : OnStateExitFromPOSE30(animator, stateInfo); break;
				case StateIdPOSE31 : OnStateExitFromPOSE31(animator, stateInfo); break;
				case StateIdFace_angry1_unitychan : OnStateExitFromFace_angry1_unitychan(animator, stateInfo); break;
				case StateIdFace_sap_unitychan : OnStateExitFromFace_sap_unitychan(animator, stateInfo); break;
				case StateIdFace_conf_unitychan : OnStateExitFromFace_conf_unitychan(animator, stateInfo); break;
				case StateIdFace_smile2_unitychan : OnStateExitFromFace_smile2_unitychan(animator, stateInfo); break;
				case StateIdFace_eye_close_unitychan : OnStateExitFromFace_eye_close_unitychan(animator, stateInfo); break;
				case StateIdFace_smile1_unitychan : OnStateExitFromFace_smile1_unitychan(animator, stateInfo); break;
				case StateIdFace_angry2_unitychan : OnStateExitFromFace_angry2_unitychan(animator, stateInfo); break;
				case StateIdFace_default_unitychan : OnStateExitFromFace_default_unitychan(animator, stateInfo); break;
				case StateIdFace_default_unitychan0 : OnStateExitFromFace_default_unitychan0(animator, stateInfo); break;
				case StateIdFace_disstract1_unitychan : OnStateExitFromFace_disstract1_unitychan(animator, stateInfo); break;
				case StateIdFace_disstract2_unitychan : OnStateExitFromFace_disstract2_unitychan(animator, stateInfo); break;

			}
		}

		public override void OnStateMachineEnter(Animator animator, int stateMachinePathHash)
		{
			//スクリプトが貼り付けられたステートマシンに遷移してきた時に実行
			
		}

		public override void OnStateMachineExit(Animator animator, int stateMachinePathHash)
		{
			//スクリプトが貼り付けられたステートマシンから出て行く時に実行			
			
		}
		/*
		public override void OnStateMove(Animator animator, AnimatorStateInfo stateInfo, int layerIndex)
		{
			//MonoBehaviour.OnAnimatorMoveの直後に実行される
			switch(layerIndex)
			{
				// case 
				case StateIdPOSE01 : OnStateMovePOSE01(animator, stateInfo); break;
				case StateIdPOSE02 : OnStateMovePOSE02(animator, stateInfo); break;
				case StateIdPOSE03 : OnStateMovePOSE03(animator, stateInfo); break;
				case StateIdPOSE04 : OnStateMovePOSE04(animator, stateInfo); break;
				case StateIdPOSE05 : OnStateMovePOSE05(animator, stateInfo); break;
				case StateIdPOSE06 : OnStateMovePOSE06(animator, stateInfo); break;
				case StateIdPOSE07 : OnStateMovePOSE07(animator, stateInfo); break;
				case StateIdPOSE08 : OnStateMovePOSE08(animator, stateInfo); break;
				case StateIdPOSE09 : OnStateMovePOSE09(animator, stateInfo); break;
				case StateIdPOSE10 : OnStateMovePOSE10(animator, stateInfo); break;
				case StateIdPOSE11 : OnStateMovePOSE11(animator, stateInfo); break;
				case StateIdPOSE12 : OnStateMovePOSE12(animator, stateInfo); break;
				case StateIdPOSE13 : OnStateMovePOSE13(animator, stateInfo); break;
				case StateIdPOSE14 : OnStateMovePOSE14(animator, stateInfo); break;
				case StateIdPOSE15 : OnStateMovePOSE15(animator, stateInfo); break;
				case StateIdPOSE16 : OnStateMovePOSE16(animator, stateInfo); break;
				case StateIdPOSE17 : OnStateMovePOSE17(animator, stateInfo); break;
				case StateIdPOSE18 : OnStateMovePOSE18(animator, stateInfo); break;
				case StateIdPOSE19 : OnStateMovePOSE19(animator, stateInfo); break;
				case StateIdPOSE20 : OnStateMovePOSE20(animator, stateInfo); break;
				case StateIdPOSE21 : OnStateMovePOSE21(animator, stateInfo); break;
				case StateIdPOSE22 : OnStateMovePOSE22(animator, stateInfo); break;
				case StateIdPOSE23 : OnStateMovePOSE23(animator, stateInfo); break;
				case StateIdPOSE24 : OnStateMovePOSE24(animator, stateInfo); break;
				case StateIdPOSE25 : OnStateMovePOSE25(animator, stateInfo); break;
				case StateIdPOSE26 : OnStateMovePOSE26(animator, stateInfo); break;
				case StateIdPOSE27 : OnStateMovePOSE27(animator, stateInfo); break;
				case StateIdPOSE28 : OnStateMovePOSE28(animator, stateInfo); break;
				case StateIdPOSE29 : OnStateMovePOSE29(animator, stateInfo); break;
				case StateIdPOSE30 : OnStateMovePOSE30(animator, stateInfo); break;
				case StateIdPOSE31 : OnStateMovePOSE31(animator, stateInfo); break;
				case StateIdFace_angry1_unitychan : OnStateMoveFace_angry1_unitychan(animator, stateInfo); break;
				case StateIdFace_sap_unitychan : OnStateMoveFace_sap_unitychan(animator, stateInfo); break;
				case StateIdFace_conf_unitychan : OnStateMoveFace_conf_unitychan(animator, stateInfo); break;
				case StateIdFace_smile2_unitychan : OnStateMoveFace_smile2_unitychan(animator, stateInfo); break;
				case StateIdFace_eye_close_unitychan : OnStateMoveFace_eye_close_unitychan(animator, stateInfo); break;
				case StateIdFace_smile1_unitychan : OnStateMoveFace_smile1_unitychan(animator, stateInfo); break;
				case StateIdFace_angry2_unitychan : OnStateMoveFace_angry2_unitychan(animator, stateInfo); break;
				case StateIdFace_default_unitychan : OnStateMoveFace_default_unitychan(animator, stateInfo); break;
				case StateIdFace_default_unitychan0 : OnStateMoveFace_default_unitychan0(animator, stateInfo); break;
				case StateIdFace_disstract1_unitychan : OnStateMoveFace_disstract1_unitychan(animator, stateInfo); break;
				case StateIdFace_disstract2_unitychan : OnStateMoveFace_disstract2_unitychan(animator, stateInfo); break;

			}
		}
		*/
		public override void OnStateUpdate(Animator animator, AnimatorStateInfo stateInfo, int layerIndex)
		{
			//最初と最後のフレームを除く、各フレーム単位で実行
			switch(layerIndex)
			{
				// case 
				case StateIdPOSE01 : OnStateUpdatePOSE01(animator, stateInfo); break;
				case StateIdPOSE02 : OnStateUpdatePOSE02(animator, stateInfo); break;
				case StateIdPOSE03 : OnStateUpdatePOSE03(animator, stateInfo); break;
				case StateIdPOSE04 : OnStateUpdatePOSE04(animator, stateInfo); break;
				case StateIdPOSE05 : OnStateUpdatePOSE05(animator, stateInfo); break;
				case StateIdPOSE06 : OnStateUpdatePOSE06(animator, stateInfo); break;
				case StateIdPOSE07 : OnStateUpdatePOSE07(animator, stateInfo); break;
				case StateIdPOSE08 : OnStateUpdatePOSE08(animator, stateInfo); break;
				case StateIdPOSE09 : OnStateUpdatePOSE09(animator, stateInfo); break;
				case StateIdPOSE10 : OnStateUpdatePOSE10(animator, stateInfo); break;
				case StateIdPOSE11 : OnStateUpdatePOSE11(animator, stateInfo); break;
				case StateIdPOSE12 : OnStateUpdatePOSE12(animator, stateInfo); break;
				case StateIdPOSE13 : OnStateUpdatePOSE13(animator, stateInfo); break;
				case StateIdPOSE14 : OnStateUpdatePOSE14(animator, stateInfo); break;
				case StateIdPOSE15 : OnStateUpdatePOSE15(animator, stateInfo); break;
				case StateIdPOSE16 : OnStateUpdatePOSE16(animator, stateInfo); break;
				case StateIdPOSE17 : OnStateUpdatePOSE17(animator, stateInfo); break;
				case StateIdPOSE18 : OnStateUpdatePOSE18(animator, stateInfo); break;
				case StateIdPOSE19 : OnStateUpdatePOSE19(animator, stateInfo); break;
				case StateIdPOSE20 : OnStateUpdatePOSE20(animator, stateInfo); break;
				case StateIdPOSE21 : OnStateUpdatePOSE21(animator, stateInfo); break;
				case StateIdPOSE22 : OnStateUpdatePOSE22(animator, stateInfo); break;
				case StateIdPOSE23 : OnStateUpdatePOSE23(animator, stateInfo); break;
				case StateIdPOSE24 : OnStateUpdatePOSE24(animator, stateInfo); break;
				case StateIdPOSE25 : OnStateUpdatePOSE25(animator, stateInfo); break;
				case StateIdPOSE26 : OnStateUpdatePOSE26(animator, stateInfo); break;
				case StateIdPOSE27 : OnStateUpdatePOSE27(animator, stateInfo); break;
				case StateIdPOSE28 : OnStateUpdatePOSE28(animator, stateInfo); break;
				case StateIdPOSE29 : OnStateUpdatePOSE29(animator, stateInfo); break;
				case StateIdPOSE30 : OnStateUpdatePOSE30(animator, stateInfo); break;
				case StateIdPOSE31 : OnStateUpdatePOSE31(animator, stateInfo); break;
				case StateIdFace_angry1_unitychan : OnStateUpdateFace_angry1_unitychan(animator, stateInfo); break;
				case StateIdFace_sap_unitychan : OnStateUpdateFace_sap_unitychan(animator, stateInfo); break;
				case StateIdFace_conf_unitychan : OnStateUpdateFace_conf_unitychan(animator, stateInfo); break;
				case StateIdFace_smile2_unitychan : OnStateUpdateFace_smile2_unitychan(animator, stateInfo); break;
				case StateIdFace_eye_close_unitychan : OnStateUpdateFace_eye_close_unitychan(animator, stateInfo); break;
				case StateIdFace_smile1_unitychan : OnStateUpdateFace_smile1_unitychan(animator, stateInfo); break;
				case StateIdFace_angry2_unitychan : OnStateUpdateFace_angry2_unitychan(animator, stateInfo); break;
				case StateIdFace_default_unitychan : OnStateUpdateFace_default_unitychan(animator, stateInfo); break;
				case StateIdFace_default_unitychan0 : OnStateUpdateFace_default_unitychan0(animator, stateInfo); break;
				case StateIdFace_disstract1_unitychan : OnStateUpdateFace_disstract1_unitychan(animator, stateInfo); break;
				case StateIdFace_disstract2_unitychan : OnStateUpdateFace_disstract2_unitychan(animator, stateInfo); break;

			}
		}

		public override void OnStateIK(Animator animator, AnimatorStateInfo stateInfo, int layerIndex)
		{
			//MonoBehaviour.OnAnimatorIKの直後に実行される
			switch(layerIndex)
			{
				// case 
				case StateIdPOSE01 : OnStateIkPOSE01(animator, stateInfo); break;
				case StateIdPOSE02 : OnStateIkPOSE02(animator, stateInfo); break;
				case StateIdPOSE03 : OnStateIkPOSE03(animator, stateInfo); break;
				case StateIdPOSE04 : OnStateIkPOSE04(animator, stateInfo); break;
				case StateIdPOSE05 : OnStateIkPOSE05(animator, stateInfo); break;
				case StateIdPOSE06 : OnStateIkPOSE06(animator, stateInfo); break;
				case StateIdPOSE07 : OnStateIkPOSE07(animator, stateInfo); break;
				case StateIdPOSE08 : OnStateIkPOSE08(animator, stateInfo); break;
				case StateIdPOSE09 : OnStateIkPOSE09(animator, stateInfo); break;
				case StateIdPOSE10 : OnStateIkPOSE10(animator, stateInfo); break;
				case StateIdPOSE11 : OnStateIkPOSE11(animator, stateInfo); break;
				case StateIdPOSE12 : OnStateIkPOSE12(animator, stateInfo); break;
				case StateIdPOSE13 : OnStateIkPOSE13(animator, stateInfo); break;
				case StateIdPOSE14 : OnStateIkPOSE14(animator, stateInfo); break;
				case StateIdPOSE15 : OnStateIkPOSE15(animator, stateInfo); break;
				case StateIdPOSE16 : OnStateIkPOSE16(animator, stateInfo); break;
				case StateIdPOSE17 : OnStateIkPOSE17(animator, stateInfo); break;
				case StateIdPOSE18 : OnStateIkPOSE18(animator, stateInfo); break;
				case StateIdPOSE19 : OnStateIkPOSE19(animator, stateInfo); break;
				case StateIdPOSE20 : OnStateIkPOSE20(animator, stateInfo); break;
				case StateIdPOSE21 : OnStateIkPOSE21(animator, stateInfo); break;
				case StateIdPOSE22 : OnStateIkPOSE22(animator, stateInfo); break;
				case StateIdPOSE23 : OnStateIkPOSE23(animator, stateInfo); break;
				case StateIdPOSE24 : OnStateIkPOSE24(animator, stateInfo); break;
				case StateIdPOSE25 : OnStateIkPOSE25(animator, stateInfo); break;
				case StateIdPOSE26 : OnStateIkPOSE26(animator, stateInfo); break;
				case StateIdPOSE27 : OnStateIkPOSE27(animator, stateInfo); break;
				case StateIdPOSE28 : OnStateIkPOSE28(animator, stateInfo); break;
				case StateIdPOSE29 : OnStateIkPOSE29(animator, stateInfo); break;
				case StateIdPOSE30 : OnStateIkPOSE30(animator, stateInfo); break;
				case StateIdPOSE31 : OnStateIkPOSE31(animator, stateInfo); break;
				case StateIdFace_angry1_unitychan : OnStateIkFace_angry1_unitychan(animator, stateInfo); break;
				case StateIdFace_sap_unitychan : OnStateIkFace_sap_unitychan(animator, stateInfo); break;
				case StateIdFace_conf_unitychan : OnStateIkFace_conf_unitychan(animator, stateInfo); break;
				case StateIdFace_smile2_unitychan : OnStateIkFace_smile2_unitychan(animator, stateInfo); break;
				case StateIdFace_eye_close_unitychan : OnStateIkFace_eye_close_unitychan(animator, stateInfo); break;
				case StateIdFace_smile1_unitychan : OnStateIkFace_smile1_unitychan(animator, stateInfo); break;
				case StateIdFace_angry2_unitychan : OnStateIkFace_angry2_unitychan(animator, stateInfo); break;
				case StateIdFace_default_unitychan : OnStateIkFace_default_unitychan(animator, stateInfo); break;
				case StateIdFace_default_unitychan0 : OnStateIkFace_default_unitychan0(animator, stateInfo); break;
				case StateIdFace_disstract1_unitychan : OnStateIkFace_disstract1_unitychan(animator, stateInfo); break;
				case StateIdFace_disstract2_unitychan : OnStateIkFace_disstract2_unitychan(animator, stateInfo); break;

			}
		}
	}
}